jobs:
- job: ubuntu_latest
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: cache-platform-dependencies.yml
    parameters:
      platform: ubuntu-latest

- job: ubuntu_legacy
  pool:
    vmImage: ubuntu-18.04
  steps:
  - template: cache-platform-dependencies.yml
    parameters:
      platform: ubuntu-legacy

- job: windows
  pool:
    vmImage: windows-latest
  steps:
  - template: cache-platform-dependencies.yml
    parameters:
      platform: windows

- job: macos
  pool:
    vmImage: macOS-latest
  steps:
  - template: cache-platform-dependencies.yml
    parameters:
      platform: macos
