trigger:
  branches:
    exclude: [ l10n_master ]

jobs:
  - job: debug
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        pip install -U pip setuptools twine wheel

        export NNI_RELEASE=999.0
        python setup.py bdist_wheel -p manylinux1_x86_64

    - task: TwineAuthenticate@1
      inputs:
        artifactFeed: NNIOpenSource/sandbox

    - script: |
        python -m twine upload -r sandbox --config-file $(PYPIRC_PATH) dist/*.whl
